### ISSUE TITLE
Jeroennoten's fork bricks NPM on windows

### ISSUE THREAD

**Issue by theomessin** [JeffreyWay/laravel-elixir-webpack-official#33]
I keep getting the following error when I run `npm install`:

```
npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\theomessin\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jeroennoten-webpack-stream-git-patch-1-b24e730a C:\Users\theomessin\.babun\cygwin\tmp\npm-5592-757ae565\git-cache-5b8cebbf\d78a3568e259f9cdbc64c60290639af6ef6d3baf
npm ERR! Cloning into 'C:\Users\theomessin\.babun\cygwin\tmp\npm-5592-757ae565\git-cache-5b8cebbf\d78a3568e259f9cdbc64c60290639af6ef6d3baf'...
npm ERR! fatal: '/cygdrive/c/Users/theomessin/AppData/Roaming/npm-cache/_git-remotes/git-github-com-jeroennoten-webpack-stream-git-patch-1-b24e730a/C:\Users\theomessin\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jeroennoten-webpack-stream-git-patch-1-b24e730a' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

After investigating this, I believe that the reason behind this is line 28 of commit ac6aa6507252a74eb9c970548680c4117b6de27d. Any ideas?

**Comment by theomessin** [comment]
I did some digging around and I have resolved the issue. It had to do with the version of git that babun was using. Updating git should fix this issue.

**Comment by grlira** [comment]
I'm having the same problem. Running npm under cygwin on Windows 8. Tried updating git trough cygwin, but the lastest version available is 2.8.3., so I downloaded/compiled/installed 2.10.2. Still getting the same error. Any suggestions?

**Comment by grlira** [comment]
As a temporary fix, I added a npm-shrinkwrap.json file to my project folder with the following content:
`{
    "dependencies": {
        "laravel-elixir-webpack-official": {
            "version": "1.0.9",
            "from": "laravel-elixir-webpack-official@1.0.9",
            "dependencies": {
                "webpack-stream": {
                    "version": "^3.2.0",
                    "from": "webpack-stream@3.2.0"
                }
            }
        }
    }
}
`

but the root problem persists.
